<?php
declare(strict_types=1);

require_once $_SERVER['DOCUMENT_ROOT'].'/rwa/inc/core/bootstrap.php';

use Dompdf\Dompdf;

$pdo = $GLOBALS['pdo'];

function val($q) {
    global $pdo;
    return $pdo->query($q)->fetchColumn() ?: 0;
}

// ===== DATA =====
$totalIssued = val("SELECT COUNT(*) FROM poado_rwa_certs");
$totalMinted = val("SELECT COUNT(*) FROM poado_rwa_certs WHERE status='minted'");
$totalSales  = val("SELECT SUM(sale_amount_ton) FROM poado_rwa_royalty_events_v2");
$totalRoyalty= val("SELECT SUM(royalty_amount_ton) FROM poado_rwa_royalty_events_v2");

$holderPool  = val("SELECT SUM(holder_pool_ton) FROM poado_rwa_royalty_events_v2");
$acePool     = val("SELECT SUM(ace_pool_ton) FROM poado_rwa_royalty_events_v2");
$goldPool    = val("SELECT SUM(gold_packet_pool_ton) FROM poado_rwa_royalty_events_v2");
$treasury    = val("SELECT SUM(treasury_retained_ton) FROM poado_rwa_royalty_events_v2");

$unclaimed   = val("SELECT SUM(amount_ton) FROM poado_rwa_claims WHERE claimed=0");

$date = date('Y-m-d H:i:s');

// ===== HTML =====
$html = "
<html>
<head>
<style>
body { font-family: DejaVu Sans; }
h1 { text-align:center; }
.table { width:100%; border-collapse:collapse; }
.table td { padding:8px; border-bottom:1px solid #ccc; }
</style>
</head>
<body>

<h1>RWA INVESTOR REPORT</h1>

<p>Date: {$date}</p>

<h2>Overview</h2>
<table class='table'>
<tr><td>Total Issued</td><td>{$totalIssued}</td></tr>
<tr><td>Total Minted</td><td>{$totalMinted}</td></tr>
<tr><td>Total Sales (TON)</td><td>{$totalSales}</td></tr>
<tr><td>Total Royalty (TON)</td><td>{$totalRoyalty}</td></tr>
</table>

<h2>Distribution</h2>
<table class='table'>
<tr><td>Holder Pool</td><td>{$holderPool}</td></tr>
<tr><td>ACE Pool</td><td>{$acePool}</td></tr>
<tr><td>Gold Packet Vault</td><td>{$goldPool}</td></tr>
<tr><td>Treasury</td><td>{$treasury}</td></tr>
</table>

<h2>Liability</h2>
<table class='table'>
<tr><td>Unclaimed TON</td><td>{$unclaimed}</td></tr>
</table>

<br><br>

<p>Generated by RWA System</p>

</body>
</html>
";

// ===== PDF =====
require_once $_SERVER['DOCUMENT_ROOT'].'/rwa/cert/vendor/autoload.php';

$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

$filename = "RWA_Report_" . date('Ymd_His') . ".pdf";

header("Content-Type: application/pdf");
header("Content-Disposition: inline; filename=$filename");

echo $dompdf->output();
